reproduction for bug in #2619
# Steps to reproduce
1. Checkout this PR locally
2. Run `cargo run -Funstable-mobile-app -- mobile-app upload tests/integration/_fixtures/mobile_app/unexpected.ipa --log-level=debug`
3. Observe following the following error, which occurs despite the presence of `Payload/DemoApp.app/Info.plist`, because `Payload/s/demo.app/Info.plist` is shorter in terms of number of characters.

```
error: Failed to convert IPA to XCArchive for file tests/integration/_fixtures/mobile_app/unexpected.ipa

Caused by:
    No .app found in IPA
```